version: '3.6'

services:
  postgres:
    build: ./postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
    ports:
      - "5432:5432"
  face-recognition-api:
    build: ./
    working_dir: /home/node/face-recognition-api
    environment:
      POSTGRES_URL: ${POSTGRES_URL_API}
      REDIS_URL: ${REDIS_URL}
    command: npm run dev
    ports: 
      - "3000:3000"
    volumes:
      - ./:/home/node/face-recognition-api
  redis:
    restart: always
    image: redis
    ports:
      - "6379:6379"